[package]
edition = "2021"
name = "hello-rs"
version = "2.2.0"

[dependencies]
argparse = "0.2"
chrono = "0.4"
file_diff = "1.0.0"
mpris = "1.1"
once_cell = "1.10"
openweathermap = "0.2"
serde_json = "1.0"
substring = "1.4"
sys-info = "0.9.1"
systemstat = "0.1"
tokio = {version = "1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
unicode-segmentation = "1.9"
whoami = "1.2.1"
